---
- name: Delete | import common tasks
  tags: mariadb
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | import stop tasks
  tags: mariadb
  ansible.builtin.import_tasks: "stop.yml"

- name: Delete | purge mariadb packages
  tags: mariadb
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: true
    purge: true
    state: absent
  loop: "{{ mariadb_pkgs }}"
  become: true
  when: inventory_hostname in groups['mariadb']
...
