---
- name: Delete | import common tasks
  tags:
    - mariadb
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | remove packages
  tags:
    - mariadb
    - pbos-infra
  ansible.builtin.apt:
    name: "{{ item }}*"
    state: absent
  loop: "{{ packages }}"
  become: true

- name: Delete | remove directory
  tags:
    - mariadb
    - pbos-infra
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/mysql
    - /etc/mysql
  become: true
...
