---
- name: Secure | set root password
  community.mysql.mysql_user:
    login_unix_socket: "{{ service_socket }}"
    name: "root"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    priv: "*.*:ALL,GRANT"
  loop:
    - 127.0.0.1
    - localhost
  become: true
  delegate_to: "{{ groups['mariadb'][0] }}"
  run_once: true
  no_log: true

- name: Secure | alter mysql user priviliges
  community.mysql.mysql_user:
    login_unix_socket: "{{ service_socket }}"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "mysql"
    plugin: unix_socket
    priv: "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR"
  become: true
  no_log: true

- name: Secure | set .my.cnf file for user
  ansible.builtin.template:
    src: "dotmy.cnf.j2"
    dest: "{{ ansible_env.HOME }}/.my.cnf"
    mode: "0600"

- name: Secure | set .my.cnf file for root
  ansible.builtin.template:
    src: "dotmy.cnf.j2"
    dest: "/root/.my.cnf"
    mode: "0600"
  become: true
...
