---
- name: Start | import common tasks
  tags: mariadb
  ansible.builtin.import_tasks: "common.yml"

- name: Start | get bootstrap server
  tags: mariadb
  ansible.builtin.lineinfile:
    path: "{{ grastate_file }}"
    line: "safe_to_bootstrap: 1"
    state: present
  check_mode: true
  become: true
  register: safe_to_bootstrap

- name: Start | get the server that can bootstrap safely
  tags: mariadb
  set_fact:
    bootstrap: "{{ safe_to_bootstrap.changed | ternary(false, true) }}"

- name: Start | show bootstrap
  tags: mariadb
  debug:
    msg: "{{ bootstrap }}"

- name: Start | start service on bootstrap server
  tags: mariadb
  block:
    - name: set systemd environment
      shell: |
        systemctl import-environment _WSREP_NEW_CLUSTER
      args:
        executable: /bin/bash
      environment:
        _WSREP_NEW_CLUSTER: "--wsrep-new-cluster"
      become: true
      when: bootstrap
    - name: start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
        enabled: true
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ systemd_service_name }}"
      when: bootstrap
    - name: wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ mariadb_port }}"
        delay: 5
        sleep: 2
        timeout: 20
        state: started
      when: bootstrap

- name: Start | start service on other server
  tags: mariadb
  block:
    - name: start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ systemd_service_name }}"
      when: not bootstrap
    - name: wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ mariadb_port }}"
        sleep: 2
        timeout: 10
        state: started
      when: not bootstrap
...
